<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Success"
		duration="4.5m"
		durationms="272333"
		type="root"
		rid="13e88fffed6493c1"
		totalerrorcount="2"
		totalwarningcount="1"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="1"
		totalblockedtestcasecount="0"
		childsuccesscount="1"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="1"
		totalfailedcount="1"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="DangTranPTN"
		rxversion="10.1.2.0"
		host="DESKTOP-DTRR79V"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-US"
		screenresolution="1920x1080"
		timestamp="11/17/2021 8:59:40 AM"
		timestampiso="2021-11-17T01:59:40"
		endtime="11/17/2021 9:04:12 AM"
		timeoutfactor="1"
		runid=""
		sutversion="">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Success"
			duration="4.5m"
			durationms="267359"
			type="test-suite"
			rid="3ae7d5d6efc3f6c"
			totalerrorcount="2"
			totalwarningcount="1"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="1"
			totalblockedtestcasecount="0"
			childsuccesscount="0"
			childfailedcount="1"
			childblockedcount="0"
			totalsuccesscount="1"
			totalfailedcount="1"
			totalblockedcount="0"
			totalmaintenancemodecount="0"
			testsuitename="MBA_Add_Product"
			headertext="MBA_Add_Product"
			runconfigname="TestRun"
			runlabel="">
			<params>
			</params>
			<errormessage>
				An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Thread was being aborted.
   at Ranorex.Core.Testing.TestModuleLeaf.Run(DataContext parentDataContext, Boolean childSkip)
   at Ranorex.Core.Testing.TearDownNode.Run(DataContext parentDataContext, Boolean _childSkip)
   at Ranorex.Core.Testing.TestCaseNode.RunTeardownContainer(TestResult overallResult, Boolean childSkip)
   at Ranorex.Core.Testing.TestCaseNode.RunChildren(Boolean childSkip, RetryInfo retryInfo)
   at Ranorex.Core.Testing.TestCaseNode.&lt;&gt;c__DisplayClass87_0.&lt;RunWithoutIterations&gt;b__0(RetryInfo retry)
   at Ranorex.Core.Testing.Retry.DoRetry(Func`2 operationToRetry)
   at Ranorex.Core.Testing.Retry.Do(Func`2 operationToRetry)
   at Ranorex.Core.Testing.TestCaseNode.RunWithoutIterations(Boolean childSkip)
   at Ranorex.Core.Testing.TestCaseNode.RunInternal(Boolean childSkip)
   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
			</errormessage>
			<activity
				result="Failed"
				duration="4.5m"
				durationms="267338"
				type="test-case"
				rid="15645f878fcb772d"
				totalerrorcount="2"
				totalwarningcount="1"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="4"
				childfailedcount="1"
				childblockedcount="0"
				totalsuccesscount="1"
				totalfailedcount="1"
				totalblockedcount="0"
				totalmaintenancemodecount="0"
				testcontainername="TestCase"
				testcontainerid="80dbcf13-9506-4268-bf99-d03a17850964"
				headertext="TestCase"
				displayName="TestCase"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
				<params>
					<param
						name="Username">
						auto
					</param>
					<param
						name="Password">
						Abcd@123
					</param>
				</params>
				<activity
					result="Success"
					duration="1.7s"
					durationms="1696"
					type="setup-container"
					rid="10b497b30b4514a8"
					totalerrorcount="0"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="1"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0">
					<item
						timeRelativeToTestSuiteStartTime="00:00.024"
						timeRelativeToTestModuleStartTime="00:00.005"
						timeWallClock="08:59:45"
						time="00:00.024"
						level="Info"
						category="Website">
						<message>
							Opening web site 'https://ptn-test1.oc.mbasrv.com/sbe' with browser 'Chrome' in normal mode.
						</message>
						<metainfo
							itemindex="0"
							codefile="e:\QA\TestMBA\Project1\MBA_Add_Product\OpenBrowser.cs"
							codeline="35"
							loglvl="Info">
						</metainfo>
					</item>
					<activity
						result="Success"
						duration="6ms"
						durationms="6"
						type="test-module"
						rid="1911e5d1a1c6868e"
						totalerrorcount="0"
						totalwarningcount="0"
						totalsuccesstestcasecount="0"
						totalfailedtestcasecount="0"
						totalblockedtestcasecount="0"
						childsuccesscount="0"
						childfailedcount="0"
						childblockedcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						totalmaintenancemodecount="0"
						modulename="OpenBrowser"
						displayName="OpenBrowser"
						moduleid="63c7c80b-7499-4af0-adb5-20178d9aa102"
						moduletype="UserCode"
						iteration="1"
						activity-exectype="execute"
						testentry-activity-type="testmodule">
						<varbindings>
						</varbindings>
					</activity>
				</activity>
				<activity
					result="Success"
					duration="5ms"
					durationms="5"
					type="smart-folder"
					rid="c5358d53ae8800c"
					totalerrorcount="0"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="1"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="1"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0"
					testcontainername="CommonFunctions"
					testcontainerid="4cde5141-24a2-47b7-8ea2-35a68915dbfa"
					headertext="CommonFunctions"
					displayName="CommonFunctions"
					iteration="1"
					activity-exectype="execute"
					conditionstate="none">
					<activity
						result="Success"
						duration="0ms"
						durationms="0"
						type="test-module"
						rid="e987e362eb53194"
						totalerrorcount="0"
						totalwarningcount="0"
						totalsuccesstestcasecount="0"
						totalfailedtestcasecount="0"
						totalblockedtestcasecount="0"
						childsuccesscount="0"
						childfailedcount="0"
						childblockedcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						totalmaintenancemodecount="0"
						modulename="CommonAction"
						displayName="CommonAction"
						moduleid="9e15139c-4dd3-4ce0-80de-dae7017b6771"
						moduletype="UserCode"
						iteration="1"
						activity-exectype="execute"
						testentry-activity-type="testmodule">
						<varbindings>
						</varbindings>
					</activity>
				</activity>
				<activity
					result="Success"
					duration="0ms"
					durationms="0"
					type="test-module"
					rid="8acfec3e22361f3"
					totalerrorcount="0"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0"
					modulename="ClickSubmit"
					displayName="ClickSubmit"
					moduleid="f4fddb56-8569-4715-8db7-f7daa4254842"
					moduletype="UserCode"
					iteration="1"
					activity-exectype="execute"
					testentry-activity-type="testmodule">
					<varbindings>
					</varbindings>
				</activity>
				<item
					timeRelativeToTestSuiteStartTime="01:22.639"
					timeRelativeToTestModuleStartTime="01:22.623"
					timeWallClock="09:01:07"
					time="01:22.639"
					level="Warn"
					category="WinForms">
					<message>
						Something is limiting object recognition for WinForms. This is caused by one of the following:<br/>- Your AUT uses obfuscated controls or is a mixed-mode executable.<br/>- Your AUT and the test executable target different platforms/processors. This causes issues on 64-bit OS.<br/>Process: 'HPSystemEventUtilityHost' (pid 6232)<br/>https://www.ranorex.com/help/v10.1/interfaces-connectivity/technology-instrumentation/general-troubleshooting/<br/>(This message is only shown once per report.)
					</message>
					<metainfo
						limitationName="WinFormsResolving"
						showInProgressDialog="False"
						codefile="e:\QA\TestMBA\Project1\MBA_Add_Product\LoginSuccess.cs"
						codeline="35"
						loglvl="Warn">
					</metainfo>
				</item>
				<item
					timeRelativeToTestSuiteStartTime="01:24.476"
					timeRelativeToTestModuleStartTime="01:24.460"
					timeWallClock="09:01:09"
					time="01:24.476"
					level="Info"
					category="User">
					<message>
						Item 'InputName' was found using Robust path.
					</message>
					<metainfo
						codefile="e:\QA\TestMBA\Project1\MBA_Add_Product\LoginSuccess.cs"
						codeline="35"
						loglvl="Info">
					</metainfo>
				</item>
				<activity
					result="Failed"
					duration="28ms"
					durationms="28"
					type="test-module"
					rid="120382808e678f8"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0"
					modulename="LoginSuccess"
					displayName="LoginSuccess"
					moduleid="0b60331a-8dc8-473a-8360-8bc7d3e3d96d"
					moduletype="UserCode"
					iteration="1"
					activity-exectype="runiteration"
					testentry-activity-type="testmodule">
					<errormessage>
						Exception has been thrown by the target of an invocation.
					</errormessage>
					<item
						timeRelativeToTestSuiteStartTime="01:24.536"
						timeRelativeToTestModuleStartTime="00:00.002"
						timeWallClock="09:01:09"
						time="01:24.536"
						level="Error"
						category="Module">
						<message>
							Exception has been thrown by the target of an invocation.<br/>Failed to wait for item to exist.<br/>Failed to find item 'MBA_Add_ProductRepository.MBA.LoginPage.InputName'.<br/>No element found for path '/dom[@domain='ptn-test1.oc.mbasrv.com']//input[@id='input-username']' at step 'element' after 35 attempts within 2s.
						</message>
						<metainfo
							stacktrace="   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#13;&#10;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#13;&#10;   at System.Activator.CreateInstance(Type type)&#13;&#10;   at Ranorex.Core.Testing.TestModuleActivator.DefaultFactoryMethod.CreateFactory()&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.InitializeTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.GetTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.RunWithRepeats(DataContext parentDataContext, ErrorBehavior errorBehavior)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.Run(DataContext parentDataContext, Boolean childSkip)"
							loglvl="Error">
						</metainfo>
					</item>
				</activity>
				<activity
					result="Success"
					duration="3m"
					durationms="182790"
					type="teardown-container"
					rid="9b3d1daf841368"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="1"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0">
					<activity
						result="Failed"
						duration="46ms"
						durationms="46"
						type="test-module"
						rid="1f17550fc8ab0985"
						totalerrorcount="1"
						totalwarningcount="0"
						totalsuccesstestcasecount="0"
						totalfailedtestcasecount="0"
						totalblockedtestcasecount="0"
						childsuccesscount="0"
						childfailedcount="0"
						childblockedcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						totalmaintenancemodecount="0"
						modulename="CloseBrowser"
						displayName="CloseBrowser"
						moduleid="4775aa69-db99-4825-9714-e8aba4273683"
						moduletype="UserCode"
						iteration="1"
						activity-exectype="runiteration"
						testentry-activity-type="testmodule">
						<errormessage>
							Thread was being aborted.
						</errormessage>
						<item
							timeRelativeToTestSuiteStartTime="04:27.319"
							timeRelativeToTestModuleStartTime="00:00.018"
							timeWallClock="09:04:12"
							time="04:27.319"
							level="Error"
							category="Module">
							<message>
								Thread was being aborted.
							</message>
							<metainfo
								stacktrace="   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#13;&#10;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#13;&#10;   at System.Activator.CreateInstance(Type type)&#13;&#10;   at Ranorex.Core.Testing.TestModuleActivator.DefaultFactoryMethod.CreateFactory()&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.InitializeTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.GetTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.RunWithRepeats(DataContext parentDataContext, ErrorBehavior errorBehavior)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.Run(DataContext parentDataContext, Boolean childSkip)"
								loglvl="Error">
							</metainfo>
						</item>
					</activity>
				</activity>
			</activity>
		</activity>
		<item
			timeRelativeToTestSuiteStartTime="04:32.302"
			timeRelativeToTestModuleStartTime="04:32.302"
			timeWallClock="09:04:12"
			time="04:32.302"
			level="Failure"
			category="TestSuite">
			<message>
				Thread was being aborted.
			</message>
			<metainfo
				stacktrace="   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)&#13;&#10;   at Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.TryRunTestSuite(RunParams rp, TestSuite testSuite)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.&lt;>c__DisplayClass13_1.&lt;RunInternal>b__6()&#13;&#10;   at Ranorex.Common.Types.OptCombinators.UnwrapOrElse[T](Opt`1 self, Func`1 generator)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String[] testSuiteXmls, RunParams[] rps)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
